name: arnhss
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  provider: ^6.0.3
  dio: ^4.0.6
  flutter_otp_text_field: ^1.1.0
  flutter_keyboard_visibility: ^5.3.0
  lottie: ^1.4.1
  dotted_border: ^2.0.0+2
  http: ^0.13.5
  get: ^4.6.5
  otp_text_field: ^1.1.3
  google_fonts: ^3.0.1
  remixicon: ^1.0.0
  flashy_tab_bar2: ^0.0.4
  rounded_tabbar_widget: ^0.0.2
  flutter_staggered_grid_view: ^0.6.2
  table_calendar: ^3.0.6
  intl: ^0.17.0
  pie_chart: ^5.3.2
  flutter_launcher_icons: "^0.10.0"
  cached_network_image: ^3.2.1
  flutter_native_splash: ^2.2.8
  flutter_calendar_carousel: ^2.4.0
  shimmer: ^2.0.0
  timeline_tile: ^2.0.0
  flutter_slidable: ^2.0.0
  uuid: ^3.0.6
  sqflite: ^2.1.0
  flutter_pdfview: ^1.2.5
  path_provider: ^2.0.11
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  shared_preferences: ^2.0.15
  firebase_database: ^9.1.7
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^13.1.0
  flutter_dotenv: ^5.0.2
  custom_refresh_indicator: ^2.0.1
  syncfusion_flutter_charts: ^20.3.59
  fpdart: ^0.3.0
  firebase_storage: ^10.3.11
  file_picker: ^5.2.4
  image_picker: ^0.8.6
  # number_slide_animation: ^0.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher/1024.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pngs/
    - assets/data/
    - assets/lottie/
    - assets/images/icons/
    - assets/images/ic_launcher/1024.png
    - assets/images/pngs/notes/
    - .env
